version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/msa-infra

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 60
      runas: ubuntu
      